### ISSUE TITLE
bug on new kernel

### ISSUE THREAD

**Issue by fehim-proses** [Zibri/Realtek-rts5229-linux-driver#13]
Error! Bad return status for module build on kernel: 5.4.0-96-generic (x86_64)
Consult /var/lib/dkms/rts-5229/1.05sutton9/build/make.log for more information.
dpkg: error processing package rts-5229-dkms (--configure):
 installed rts-5229-dkms package post-installation script subprocess returned er
ror exit status 10
Errors were encountered while processing:
 rts-5229-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

in log file

/var/lib/dkms/rts-5229/1.05sutton9/build/rtsx.h:193:2: error: implicit declaration of function ‘do_gettimeofday’; did you mean ‘do_settimeofday64’? [-Werror=implicit-function-declaration]
  193 |  do_gettimeofday(&tv);

Ive got this

**Comment by Zibri** [comment]
new kernels should support both 5228 both 5229. Anyway, if you find a solution, please make a pull request.
